name: Publish Docker image to Docker Hub
env:
  REGISTRY_REPO: caioqf
  IMAGE_NAME: locadora_challenge

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build -t ${{env.REGISTRY_REPO}}/${{env.IMAGE_NAME}}:${{github.sha}} .
      
  tag:
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
    - uses: actions/checkout@v3
    - name: Tag Docker image
      run: docker tag ${{env.REGISTRY_REPO}}/${{env.IMAGE_NAME}}:${{github.sha}} ${{env.REGISTRY_REPO}}/${{env.IMAGE_NAME}}:${{github.sha}}@latest
      
  publish:
    runs-on: ubuntu-latest
    needs: [tag] 
    
    steps:
    - uses: actions/checkout@v3
    - name: Publish the Docker Image
      run: docker push docker push ${{env.REGISTRY_REPO}}/${{env.IMAGE_NAME}}:${{github.sha}}@latest

