name: Publish Docker image to Docker Hub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build -t locadora_challenge:${{github.sha}} .
      
  tag_and_publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Tag Docker image
      run: docker tag locadora_challenge:${{github.sha}}@latest
      
    - uses: actions/checkout@v3
    - name: Publish the Docker Image
      run: docker push docker push caioqf/locadora_challenge:locadora_challenge:${{github.sha}}@latest

